"""
Funeral Insurance Fraud Detection — Streamlit Prototype
========================================================
Author:     Tinashe Arthur Mupindu
University: University of Zambia
Supervisor: Dr Stanley Jere

HOW TO RUN:
    1. Make sure these files are in the same folder as this script:
         insurance_claims.csv
         best_fraud_model.pkl
         scaler.pkl
         label_encoders.pkl
         feature_columns.pkl
       (All generated by running fraud_detection_pipeline.ipynb first)

    2. Open a terminal in that folder and run:
         streamlit run app.py

    3. Your browser will open automatically at http://localhost:8501
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import os

# ── Page config ───────────────────────────────────────────────────────
st.set_page_config(
    page_title="Funeral Insurance Fraud Detector",
    page_icon="🔍",
    layout="wide"
)

# ── Brand colours (CSS) ───────────────────────────────────────────────
st.markdown("""
<style>
    /* Main header */
    .main-header {
        background: linear-gradient(135deg, #1F3864 0%, #2E75B6 100%);
        padding: 1.5rem 2rem;
        border-radius: 10px;
        margin-bottom: 1.5rem;
        color: white;
    }
    .main-header h1 { color: white; margin: 0; font-size: 1.8rem; }
    .main-header p  { color: #BDD7EE; margin: 0.3rem 0 0; font-size: 0.95rem; }

    /* Result boxes */
    .result-fraud {
        background: #FFF0F0; border-left: 6px solid #C00000;
        padding: 1.2rem 1.5rem; border-radius: 8px; margin-top: 1rem;
    }
    .result-legit {
        background: #F0FFF4; border-left: 6px solid #375623;
        padding: 1.2rem 1.5rem; border-radius: 8px; margin-top: 1rem;
    }
    .metric-box {
        background: #EBF3FB; border-radius: 8px;
        padding: 0.8rem 1rem; text-align: center; margin: 0.3rem;
    }
    .metric-box .metric-val { font-size: 1.6rem; font-weight: bold; color: #1F3864; }
    .metric-box .metric-lbl { font-size: 0.75rem; color: #555; }

    /* Section divider */
    .section-title {
        color: #1F3864; font-weight: 700; font-size: 1.05rem;
        border-bottom: 2px solid #2E75B6;
        padding-bottom: 4px; margin: 1.2rem 0 0.8rem;
    }
    /* Footer */
    .footer { color: #888; font-size: 0.78rem; text-align: center; margin-top: 2rem; }
</style>
""", unsafe_allow_html=True)


# ── Load model files ──────────────────────────────────────────────────
@st.cache_resource
def load_model_files():
    required = ['best_fraud_model.pkl', 'scaler.pkl',
                 'label_encoders.pkl', 'feature_columns.pkl']
    missing = [f for f in required if not os.path.exists(f)]
    if missing:
        return None, None, None, None, missing

    with open('best_fraud_model.pkl', 'rb') as f:
        model = pickle.load(f)
    with open('scaler.pkl', 'rb') as f:
        scaler = pickle.load(f)
    with open('label_encoders.pkl', 'rb') as f:
        encoders = pickle.load(f)
    with open('feature_columns.pkl', 'rb') as f:
        feature_cols = pickle.load(f)

    return model, scaler, encoders, feature_cols, []


model, scaler, encoders, feature_cols, missing_files = load_model_files()


# ── Header ────────────────────────────────────────────────────────────
st.markdown("""
<div class="main-header">
  <h1>🔍 Funeral Insurance Fraud Detection Prototype</h1>
  <p>Application of Machine Learning and Predictive Analytics &nbsp;|&nbsp;
     University of Zambia &nbsp;|&nbsp; Tinashe Arthur Mupindu</p>
</div>
""", unsafe_allow_html=True)


# ── Missing files warning ─────────────────────────────────────────────
if missing_files:
    st.error(
        f"**Missing model files:** {', '.join(missing_files)}\n\n"
        "Please run `fraud_detection_pipeline.ipynb` first to generate these files, "
        "then restart this app."
    )
    st.stop()


# ── Sidebar — Model info ──────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 📊 Model Information")
    model_name = type(model).__name__
    display_name = "Random Forest" if "Forest" in model_name else "Logistic Regression"
    st.info(f"**Active model:** {display_name}")
    st.markdown("---")
    st.markdown("**Pipeline steps:**")
    st.markdown("""
    1. ✅ Data loaded & cleaned  
    2. ✅ Features encoded & scaled  
    3. ✅ Model trained (80% data)  
    4. ✅ Model evaluated (20% data)  
    5. ✅ Prototype deployed  
    """)
    st.markdown("---")
    st.markdown("**Evaluation metrics (test set):**")

    # Load results if available
    if os.path.exists('model_results.pkl'):
        with open('model_results.pkl', 'rb') as f:
            results = pickle.load(f)
        for k, v in results.items():
            st.markdown(f"- **{k}:** {v:.3f}")
    else:
        st.caption("Run the notebook to see live metrics here.")

    st.markdown("---")
    st.caption("⚠️ This is a proof-of-concept prototype. "
               "Do not use for live claim decisions without "
               "further validation.")


# ── Main layout ───────────────────────────────────────────────────────
st.markdown("""
Enter the details of the insurance claim below and click **Analyse Claim** to get a fraud risk prediction.
""")

col_left, col_right = st.columns([1, 1], gap="large")

with col_left:
    st.markdown('<div class="section-title">👤 Policyholder Details</div>',
                unsafe_allow_html=True)

    months_as_customer = st.slider(
        "Months as customer", 0, 500, 120,
        help="How long the policyholder has been a customer."
    )
    age = st.number_input("Policyholder age", 18, 90, 35)
    insured_sex = st.selectbox("Sex", ["MALE", "FEMALE"])
    insured_education_level = st.selectbox(
        "Education level",
        ["High School", "College", "Associate", "Masters", "MD", "PhD", "JD"]
    )
    insured_occupation = st.selectbox(
        "Occupation",
        ["craft-repair", "machine-op-inspct", "sales", "armed-forces",
         "tech-support", "prof-specialty", "other-service", "priv-house-serv",
         "transport-moving", "handlers-cleaners", "adm-clerical", "farming-fishing",
         "protective-serv", "exec-managerial"]
    )
    insured_hobbies = st.selectbox(
        "Hobbies",
        ["sleeping", "reading", "board-games", "bungie-jumping", "base-jumping",
         "golf", "camping", "dancing", "skydiving", "chess", "cross-fit",
         "paintball", "polo", "kayaking", "video-games"]
    )
    insured_relationship = st.selectbox(
        "Relationship to insured",
        ["husband", "wife", "own-child", "other-relative", "unmarried", "not-in-family"]
    )

    st.markdown('<div class="section-title">📋 Policy Details</div>',
                unsafe_allow_html=True)

    policy_state = st.selectbox("Policy state", ["OH", "IN", "IL"])
    policy_csl = st.selectbox(
        "Coverage limit (CSL)", ["100/300", "250/500", "500/1000"]
    )
    policy_deductable = st.selectbox(
        "Deductible (USD)", [500, 1000, 2000]
    )
    policy_annual_premium = st.number_input(
        "Annual premium (USD)", 500.0, 3000.0, 1200.0, step=50.0
    )
    umbrella_limit = st.number_input(
        "Umbrella limit (USD)", 0, 10_000_000, 0, step=500_000
    )
    capital_gains = st.number_input("Capital gains (USD)", 0, 200_000, 0, step=1000)
    capital_loss = st.number_input("Capital loss (USD)", -200_000, 0, 0, step=1000)


with col_right:
    st.markdown('<div class="section-title">🚨 Incident Details</div>',
                unsafe_allow_html=True)

    incident_type = st.selectbox(
        "Incident type",
        ["Single Vehicle Collision", "Multi-vehicle Collision",
         "Vehicle Theft", "Parked Car"]
    )
    collision_type = st.selectbox(
        "Collision type",
        ["Side Collision", "Rear Collision", "Front Collision", "Unknown"]
    )
    incident_severity = st.selectbox(
        "Incident severity",
        ["Minor Damage", "Major Damage", "Total Loss", "Trivial Damage"]
    )
    authorities_contacted = st.selectbox(
        "Authorities contacted",
        ["Police", "Fire", "Ambulance", "Other", "Unknown"]
    )
    incident_state = st.selectbox(
        "Incident state", ["SC", "VA", "NY", "OH", "WV", "NC", "PA"]
    )
    incident_city = st.selectbox(
        "Incident city",
        ["Columbus", "Riverwood", "Arlington", "Springfield",
         "Hillsdale", "Northbend", "Northbrook"]
    )
    incident_hour = st.slider("Hour of incident (0–23)", 0, 23, 12)
    num_vehicles = st.slider("Number of vehicles involved", 1, 4, 1)
    property_damage = st.selectbox("Property damage?", ["YES", "NO", "Unknown"])
    bodily_injuries = st.slider("Bodily injuries", 0, 4, 0)
    witnesses = st.slider("Number of witnesses", 0, 4, 1)
    police_report = st.selectbox("Police report available?", ["YES", "NO", "Unknown"])

    st.markdown('<div class="section-title">💰 Claim Amounts</div>',
                unsafe_allow_html=True)

    total_claim = st.number_input("Total claim amount (USD)", 0, 200_000, 30_000, step=500)
    injury_claim = st.number_input("Injury claim (USD)", 0, 100_000, 5_000, step=500)
    property_claim = st.number_input("Property claim (USD)", 0, 100_000, 5_000, step=500)
    vehicle_claim = st.number_input("Vehicle claim (USD)", 0, 100_000, 20_000, step=500)

    st.markdown('<div class="section-title">🚗 Vehicle Details</div>',
                unsafe_allow_html=True)

    auto_make = st.selectbox(
        "Vehicle make",
        ["Toyota", "Honda", "Ford", "Chevrolet", "Dodge", "Nissan",
         "Mercedes", "BMW", "Audi", "Saab", "Subaru", "Accura", "Jeep"]
    )
    auto_year = st.slider("Vehicle year", 1995, 2025, 2010)


# ── Predict button ────────────────────────────────────────────────────
st.markdown("---")
predict_col, _, _ = st.columns([1, 2, 1])

with predict_col:
    predict_btn = st.button("🔍 Analyse Claim", use_container_width=True,
                             type="primary")

if predict_btn:
    # Build input row matching training feature order
    raw_input = {
        'months_as_customer':      months_as_customer,
        'age':                     age,
        'policy_state':            policy_state,
        'policy_csl':              policy_csl,
        'policy_deductable':       policy_deductable,
        'policy_annual_premium':   policy_annual_premium,
        'umbrella_limit':          umbrella_limit,
        'insured_sex':             insured_sex,
        'insured_education_level': insured_education_level,
        'insured_occupation':      insured_occupation,
        'insured_hobbies':         insured_hobbies,
        'insured_relationship':    insured_relationship,
        'capital-gains':           capital_gains,
        'capital-loss':            capital_loss,
        'incident_type':           incident_type,
        'collision_type':          collision_type,
        'incident_severity':       incident_severity,
        'authorities_contacted':   authorities_contacted,
        'incident_state':          incident_state,
        'incident_city':           incident_city,
        'incident_hour_of_the_day': incident_hour,
        'number_of_vehicles_involved': num_vehicles,
        'property_damage':         property_damage,
        'bodily_injuries':         bodily_injuries,
        'witnesses':               witnesses,
        'police_report_available': police_report,
        'total_claim_amount':      total_claim,
        'injury_claim':            injury_claim,
        'property_claim':          property_claim,
        'vehicle_claim':           vehicle_claim,
        'auto_make':               auto_make,
        'auto_year':               auto_year,
    }

    # Encode categoricals using saved encoders
    input_df = pd.DataFrame([raw_input])

    for col in input_df.columns:
        if col in encoders:
            enc = encoders[col]
            val = str(input_df[col].iloc[0])
            # Handle unseen labels gracefully
            if val in enc.classes_:
                input_df[col] = enc.transform([val])
            else:
                # Use most frequent class (index 0) as fallback
                input_df[col] = 0

    # Align to training feature order
    for col in feature_cols:
        if col not in input_df.columns:
            input_df[col] = 0
    input_df = input_df[feature_cols]

    # Scale
    input_scaled = scaler.transform(input_df)

    # Predict
    prediction = model.predict(input_scaled)[0]
    proba = model.predict_proba(input_scaled)[0]
    fraud_prob  = proba[1]
    legit_prob  = proba[0]

    # ── Display result ────────────────────────────────────────────────
    st.markdown("---")
    st.markdown("### 📋 Analysis Result")

    res_col1, res_col2, res_col3, res_col4 = st.columns(4)
    with res_col1:
        st.markdown(f"""
        <div class="metric-box">
          <div class="metric-val">{'🚨 FRAUD' if prediction == 1 else '✅ LEGIT'}</div>
          <div class="metric-lbl">Prediction</div>
        </div>""", unsafe_allow_html=True)
    with res_col2:
        st.markdown(f"""
        <div class="metric-box">
          <div class="metric-val" style="color:{'#C00000' if fraud_prob > 0.5 else '#375623'}">
            {fraud_prob*100:.1f}%</div>
          <div class="metric-lbl">Fraud Probability</div>
        </div>""", unsafe_allow_html=True)
    with res_col3:
        st.markdown(f"""
        <div class="metric-box">
          <div class="metric-val">{legit_prob*100:.1f}%</div>
          <div class="metric-lbl">Legitimate Probability</div>
        </div>""", unsafe_allow_html=True)
    with res_col4:
        risk = "HIGH" if fraud_prob > 0.7 else ("MEDIUM" if fraud_prob > 0.4 else "LOW")
        risk_color = "#C00000" if risk == "HIGH" else ("#C9A84C" if risk == "MEDIUM" else "#375623")
        st.markdown(f"""
        <div class="metric-box">
          <div class="metric-val" style="color:{risk_color}">{risk}</div>
          <div class="metric-lbl">Risk Level</div>
        </div>""", unsafe_allow_html=True)

    # Verdict box
    if prediction == 1:
        st.markdown(f"""
        <div class="result-fraud">
          <strong>🚨 FRAUDULENT CLAIM DETECTED</strong><br>
          This claim has been flagged as likely fraudulent with a probability of
          <strong>{fraud_prob*100:.1f}%</strong>.
          Recommended action: <strong>Refer to fraud investigation team for manual review.</strong>
        </div>""", unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div class="result-legit">
          <strong>✅ CLAIM APPEARS LEGITIMATE</strong><br>
          This claim shows a low fraud risk with a legitimacy probability of
          <strong>{legit_prob*100:.1f}%</strong>.
          Recommended action: <strong>Proceed with standard claims processing.</strong>
        </div>""", unsafe_allow_html=True)

    # Key risk flags
    st.markdown("#### ⚑ Key Risk Indicators Detected")
    flags = []
    if total_claim > 70_000:
        flags.append(f"🔴 High total claim amount (USD {total_claim:,})")
    if incident_severity == "Total Loss":
        flags.append("🔴 Claim involves total loss of vehicle")
    if police_report == "Unknown" or police_report == "NO":
        flags.append("🟡 No police report available")
    if witnesses == 0:
        flags.append("🟡 No witnesses recorded")
    if property_damage == "Unknown":
        flags.append("🟡 Property damage status unknown")
    if collision_type == "Unknown":
        flags.append("🟡 Collision type unknown")
    if months_as_customer < 6:
        flags.append("🔴 Very new customer (less than 6 months)")
    if capital_gains > 50_000:
        flags.append("🟡 High capital gains on record")
    if not flags:
        flags.append("🟢 No major individual risk flags identified")

    for flag in flags:
        st.markdown(f"- {flag}")

    st.caption(
        "⚠️ This prediction is generated by a machine learning model trained on historical claims data. "
        "It is a decision-support tool only and should not replace expert human judgement."
    )


# ── Footer ────────────────────────────────────────────────────────────
st.markdown("""
<div class="footer">
  Funeral Insurance Fraud Detection Prototype &nbsp;|&nbsp;
  Tinashe Arthur Mupindu &nbsp;|&nbsp; University of Zambia &nbsp;|&nbsp;
  Supervisor: Dr Stanley Jere &nbsp;|&nbsp; 2026
</div>
""", unsafe_allow_html=True)
